version: 2
jobs:
  deploy_staging:
    docker:
      - image: circleci/php
    steps:
      - checkout
      - run:
          name: Login to Staging server & Pull code
          command: ./.circleci/deploy_staging.sh
workflows:
  version: 2
  deploy:
    jobs:
      - deploy_staging:
          filters:
            branches:
              only: master

