version: 2
jobs:
  deploy_staging:
    docker:
      - image: circleci/php
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "aa:7f:aa:b0:f5:53:f3:b1:cc:4d:c4:30:e1:79:30:c9"
      - run:
          name: Login to Staging server & Pull code
          command: ./.circleci/deploy_staging.sh
workflows:
  version: 2
  deploy:
    jobs:
      - deploy_staging:
          filters:
            branches:
              only: master

